packages:
  - artifacts/*
  - lib/*
  - scripts

autoInstallPeers: false

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/express': ^5.0.6
  '@types/node': ^25.3.3
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitejs/plugin-react': ^5.0.4
  bcryptjs: ^3.0.2
  cors: ^2.8.6
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  esbuild: 0.27.3
  express: ^5.2.1
  pg: ^8.20.0
  react: 19.1.0
  react-dom: 19.1.0
  tsx: 4.21.0
  typescript: ~5.9.3
  vite: ^7.3.2
  wouter: ^3.3.5
  zod: ^3.25.76

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@replit/*'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  esbuild: 0.27.3
  '@esbuild-kit/esm-loader': npm:tsx@^4.21.0
