-- 003_product_images_full.sql — assign real product photography to EVERY catalog row (idempotent, name-based)
UPDATE products SET "imageKey" = CASE
  WHEN lower(name) LIKE '%copper%'          THEN '/products/copper-cathode.jpg'
  WHEN lower(name) LIKE '%aluminum ingot%'  THEN '/products/aluminum-ingot.jpg'
  WHEN lower(name) LIKE '%aluminum profile%'THEN '/products/aluminum-profile.jpg'
  WHEN lower(name) LIKE '%zinc%'            THEN '/products/zinc-ingot.jpg'
  WHEN lower(name) LIKE '%hot rolled%'      THEN '/products/hot-rolled-coil.jpg'
  WHEN lower(name) LIKE '%cold rolled%'     THEN '/products/steel-coil.jpg'
  WHEN lower(name) LIKE '%galvanized%'      THEN '/products/steel-coil.jpg'
  WHEN lower(name) LIKE '%stainless%'       THEN '/products/stainless-steel-sheet.jpg'
  WHEN lower(name) LIKE '%lithium carbonate%' THEN '/products/lithium-carbonate.jpg'
  WHEN lower(name) LIKE '%battery pack%'    THEN '/products/battery-pack.jpg'
  WHEN lower(name) LIKE '%caustic%'         THEN '/products/caustic-soda.jpg'
  WHEN lower(name) LIKE '%epoxy%'           THEN '/products/epoxy-resin.jpg'
  WHEN lower(name) LIKE '%titanium%'        THEN '/products/titanium-dioxide.jpg'
  WHEN lower(name) LIKE '%pump%'            THEN '/products/industrial-pump.jpg'
  WHEN lower(name) LIKE '%cnc%'             THEN '/products/cnc-machine.jpg'
  WHEN lower(name) LIKE '%injection molding%' THEN '/products/injection-machine.jpg'
  WHEN lower(name) LIKE '%compressor%'      THEN '/products/air-compressor.jpg'
  WHEN lower(name) LIKE '%motor%'           THEN '/products/induction-motor.jpg'
  WHEN lower(name) LIKE '%gearbox%'         THEN '/products/gearbox.jpg'
  WHEN lower(name) LIKE '%hydraulic press%' THEN '/products/hydraulic-press.jpg'
  WHEN lower(name) LIKE '%plc%'             THEN '/products/plc-controller.jpg'
  WHEN lower(name) LIKE '%servo%'           THEN '/products/servo-drive.jpg'
  WHEN lower(name) LIKE '%sensor%'          THEN '/products/proximity-sensors.jpg'
  WHEN lower(name) LIKE '%wheel%'           THEN '/products/alloy-wheel.jpg'
  WHEN lower(name) LIKE '%brake%'           THEN '/products/brake-disc.jpg'
  WHEN lower(name) LIKE '%valve%'           THEN '/products/engine-valves.jpg'
  WHEN lower(name) LIKE '%cement%'          THEN '/products/cement-bags.jpg'
  WHEN lower(name) LIKE '%manhole%'         THEN '/products/manhole-cover.jpg'
  WHEN lower(name) LIKE '%pvc%'             THEN '/products/pvc-pipes.jpg'
  WHEN lower(name) LIKE '%steel structure%' THEN '/products/steel-structure.jpg'
  WHEN lower(name) LIKE '%solar panel%'     THEN '/products/solar-panel.jpg'
  WHEN lower(name) LIKE '%solar inverter%'  THEN '/products/solar-inverter.jpg'
  WHEN lower(name) LIKE '%wind%'            THEN '/products/wind-blade.jpg'
  WHEN lower(name) LIKE '%corrugated%'      THEN '/products/corrugated-boxes.jpg'
  WHEN lower(name) LIKE '%kraft%'           THEN '/products/kraft-paper.jpg'
  WHEN lower(name) LIKE '%granule%'         THEN '/products/plastic-granules.jpg'
  WHEN lower(name) LIKE '%rubber%'          THEN '/products/rubber-seals.jpg'
  WHEN lower(name) LIKE '%yarn%'            THEN '/products/polyester-yarn.jpg'
  WHEN lower(name) LIKE '%antimony%'        THEN '/products/antimony-ore.jpg'
  ELSE "imageKey"
END
WHERE "imageKey" IS NULL OR lower(name) IN ('solar inverter 10kw','lithium battery pack 48v 100ah','aluminum alloy wheel rims 17"','zinc ingot 99.995%','aluminum profiles extrusion');
